AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for creating VPC Peering Connection

Resources:
  VpcPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VpcId1   # Replace with the ID of the first VPC
      PeerVpcId: !Ref VpcId2   # Replace with the ID of the second VPC
      PeerRegion: !Ref AWS::Region
      PeerRoleArn: !GetAtt VpcPeeringRole.Arn
      Tags:
        - Key: Name
          Value: MyVpcPeering

  VpcPeeringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: VpcPeeringPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AcceptVpcPeeringConnection
                  - ec2:CreateRoute
                  - ec2:DeleteRoute
                  - ec2:DescribeInstances
                  - ec2:DescribeRouteTables
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                Resource: '*'

Outputs:
  VpcPeeringConnectionId:
    Description: ID of the VPC Peering Connection
    Value: !Ref VpcPeeringConnection
